### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by dmoranj** [telefonicaid/iotagent-mqtt#84]
Current documentation is very brief and some people is having problems understanding how the IoT Agent works. This points should be improved, at least:
- Explain briefly a typical IOTA workflow with a device, including provisioning and configuration provisioning. 
- Explain the use of APIKeys and how to configure them.
- Explain the arcane ThinkingThings plugin (and add meanings to disable it using the configuration).
- Give some step-by-step guides to easily show how to start using the Agent.

**Comment by drasko** [comment]
I would suggest starting with step-by-step, few `curl` lines to get us going. IOTA's have been explained on various webinars, so this can come later. What is urgently needed is:
- provision device
- configure the system
- send message (from device)
- receive the message

**Comment by drasko** [comment]
I did some advancement and documented the steps here: https://github.com/Mainflux/mainflux-fiware/wiki/IoT-Agent-MQTT

You will find there updated documentation to do the provisioning and test the functionality via `mosquitto_pub`

**Comment by dmoranj** [comment]
The step by step goes in the last PR. I will try to improve the main README.md file also with a little more about API Keys and the missing TTPlugin explanation.

**Comment by dmoranj** [comment]
I think with #90 and #91 we cover most of the pending topics. Closing the issue.
