### ISSUE TITLE
Can provisioning be done from Orion?

### ISSUE THREAD

**Issue by drasko** [telefonicaid/iotagent-mqtt#85]
Hi,
I see that for provisioning in IoT Agents, they export and API endpoint which must be directly called from application.

From what I understand in this case, application directly calls IOTA API, and does not pass via Context Broker. Why? Isn't Context Broker a central component through all messages must flow?

I am asking this because I do not know if application can always be aware of IOTA location - when it is scaled and new Docker instances brought up they will have different IP address. How will then application discover the service (when we do not use PUB/SUB via Orion)?

Similar question goes to MQTT server - how will IOTA find horizontally scaled instances of MQTT server (hard-coded location is for one instance only, IMHO).

**Comment by dmoranj** [comment]
For access to the IOTA API in a multi instance scenario, multiple IOTAs can be instantiated behind a Load Balancer (as they are basically stateless), connected to a MongoDB cluster (that can also easily be scaled). The problem with the MQTT broker will depend on the MQTT broker itself. Some MQTT brokers support clustering, some other don't. For those not supporting clustering, as you said, the architecture should be mono-instance. 

Anyway, the horizontal scale of the IOTA layer has not been well studied yet, as we are focused on completing our components for the time being. We will update the documentation with information about how to install multiinstance IOTAs and MQTT brokers once we think we are comfortable with our solution.

**Comment by drasko** [comment]
Yes, I agree for MQTT broker. I saw that you have been in contact with Matteo Colina, Mosca MQTT broker can not be scaled without additional persistence, for example.

For my tests I am using Mosquitto, but we will probably start deployment with Mosca and see where this will go... Because of these benchmarkings: http://acro-engineer.hatenablog.com/entry/2015/06/30/100507 I started looking at [VerneMQ](https://verne.mq/) and eMQTT(http://emqtt.io/), although Kafka/Cassandra solutions can give [great results](http://fr.slideshare.net/kellogh/mqtt-kafka-33100776).

But as you said - this is a topic for later ;).

**Comment by drasko** [comment]
Anyway - this still does not answer the question: can provisioning be done from Orion?

I.e. I would like to create an app that could provision needed devices. App would send provisioning requests to the Orion (pub) which will forward it to the IoT Agent (which is subscribed to Orion).

This way application does not have to hit IoT Agent itsetlf, and does not have to care about it's IP address - it cares only about Orion, but app knows this address already - because Orion is a central pub/sub broker and everybody in the system must know it's (and only it's) address.

**Comment by dmoranj** [comment]
For the time being, that functionality (registration based on NGSI) does not exist. Devices must be provisioned via Device Provisioning API. The IoT Agent model gives the option of creating a Configuration for groups of devices, so to allow autoprovisionig of those devices in possesion of the API Key. That should ease the application from the burden of provisioning each one of the devices. But a configuration for each Service must be created in any case.

**Comment by drasko** [comment]
@dmoranj is registration based on NGSI something that is planned, or will never be implemented?

**Comment by dmoranj** [comment]
Is not currently in the backlog. Concerning its future implementation, it will depend on how the project evolve, but in the near future we have more features to add, and bugs to fix, so I guess it will be difficult. You can add a specific issue describing that enhancement, for future reference if you wish. In any case, that should belong to the IOTA Lib, not to this project (as we try to keep all the northbound interfaces implemented there, and the southbound ones in the individual IOTAs).

**Comment by dmoranj** [comment]
I'm closing this issue, as I think the question has been answered. 

If you consider this could be an interesting enhancement for the IoTAs, create an Enhancement Issue with your proposal in the IOTALib, so we have it in mind for future updates.

If there are any doubts pending concerning this issue, feel free to reopen it.
